// WARNING: File autogenerated DO NOT modify
// https://www.khronos.org/registry/OpenGL/api/GLES2/gl2.h
@file:Suppress("unused", "RedundantUnitReturnType")

package com.soywiz.kmedialayer

import kotlinx.cinterop.*
import platform.opengl32.*
import platform.windows.*
import platform.posix.*

//val String.glstr: CPointer<GLcharVar> get() = this.cstr.uncheckedCast()
val OPENGL32_DLL_MODULE: HMODULE? by lazy { LoadLibraryA("opengl32.dll") }

fun wglGetProcAddressAny(name: String): PROC? {
	return wglGetProcAddress(name)
			?: GetProcAddress(OPENGL32_DLL_MODULE, name)
			?: throw RuntimeException("Can't find GL function: '$name'")
}
